### ISSUE TITLE
ENV Variables not expanded

### ISSUE THREAD

**Issue by defel** [stuartpb/dokku-rethinkdb-plugin#7]
Hi,

I installed the dokku-rethinkdb-plugin (HEAD) on dokku-alt (HEAD). 

I have the problem, that all ENV variables except RETHINKDB_LINK_NAME  are not expanded: 

    "RDB_HOST": "$RETHINKDB_LINK_PORT_28015_TCP_ADDR",
    "RDB_PORT": "$RETHINKDB_LINK_PORT_28015_TCP_PORT",
    "RETHINKDB_LINK_NAME": "/app_env_1423425716_27225/rethinkdb_link",
    "RETHINKDB_HOST": "$RETHINKDB_LINK_PORT_28015_TCP_ADDR",
    "RETHINKDB_PORT": "$RETHINKDB_LINK_PORT_28015_TCP_PORT",

Any ideas what the problem is and how I can fix it?

**Comment by defel** [comment]
ok, it works after executing `dokku rethinkdb:bind-webui foo`

**Comment by stuartpb** [comment]
That's weird, you shouldn't have to bind the webui. In fact, binding the webui shouldn't have anything to *do* with it.

I mean, in general, I've given up on this plugin, having moved on to [Plushu](https://github.com/plushu/plushu) months ago (and having implemented a better alternative for attaching systems like RethinkDB with the [plushu-addons plugin](https://github.com/plushu/plushu-addons) about a month ago), so if users have any problems with this plugin, my only advice moving forward is pretty much going to be "install Plusku and use `addons:add rethinkdb` instead".

But I still remember what was involved in the design of this plugin, and binding explicit ports shouldn't change the way the environment variables expand, unless Dokku has made some *really weird* changes.

**Comment by defel** [comment]
maybe the reason is that I use dokku-alt instead of dokku? I thought the plugins are compatible to each other, does not seems so.

It helps me, that port binding should not be necessary - i will try some things out then

**Comment by defel** [comment]
hmm, I dont understand where the env var RETHINKDB_LINK_PORT_28015_TCP_PORT is created, it is named RETHINKDB_LINK_PORT_29015_TCP for me - is this env var set by docker?

So far, I only see that the port 49155 is created after I execute `dokku rethinkdb:bind-cluster <app>`, then the file /home/dokku/app/rethinkdb/PUBLISH is created and the env file BIND_FILE is available, in which the port is written (::29015).

I think the port 28015 should be already be created on start of the docker image, and it should be linkable to other apps. I will look into it and see if I can fix this for dokku-alt.

**Comment by stuartpb** [comment]
> hmm, I dont understand where the env var RETHINKDB_LINK_PORT_28015_TCP_PORT is created, it is named RETHINKDB_LINK_PORT_29015_TCP for me - is this env var set by docker?

Docker sets several env vars that start with `RETHINKDB_LINK_PORT_29015_TCP` when a container exposing port 28015 is linked with the name `rethinkdb-link`.

Which reminds me, this should be using the official RethinkDB Docker image now.

**Comment by defel** [comment]
tested  locally **dockerfile/rethinkdb**, looks good: 

```bash
docker run -d -p 8080:8080 -p 28015:28015 -p 29015:29015 -v /data/rethinkdb:/data dockerfile/rethinkdb 
```

**Comment by stuartpb** [comment]
`dockerfile/rethinkdb` is not the official image. `rethinkdb` is.
